<#

	ReportEmptySlots.ps1 / ngwmddgh / 2018-02-11

	Polls a BackupExec Library's slots and if any are empty, then email the list,	else quit silently.
  Useful when you have a library that should always be full of tapes.
  
  Note: You must have already bemcli.psd from BackupExec.

#>

import-module "c:\path\to\bemcli.psd1"

##### Define variables

# Which address(es) will receive the report
$recipients = "Recipient <recipientuser@domain.tld>"

# Which address will send the report
$sender = "Sender <sendinguser@domain.tld>"

# SMTP server to handle report
$SMTPserver = smtp.domain.tld

# Define the target library by its name in BackupExec
$LibraryName = "BackupExec Library Name"

# Set the number of slots in the library
$LibrarySlots = 16


##### Execute operations

# Scan the slots now to ensure accuracy
Submit-BEScanJob -RoboticLibraryDevice $LibraryName

# Sleep for 60 seconds to give the BEScanJob time to complete, since otherwise results may be inaccurate
Start-Sleep -s 60

# Create an object containing all non-cleaning slot names where BE says there is no media loaded
$EmptySlots = Get-BERoboticLibrarySlot -RoboticLibraryDevice $LibraryName | where-object {($_.Media -like '') -and !($_.IsCleaningSlot)} | Select-Object -first $LibrarySlots

if ($EmptySlots)
{

# Insert a newline between each empty slot for easy reading
$EmptySlotsList = $EmptySlots -join "`n"

$body = @"
The following slots appear empty to BackupExec, please load tapes or correct the misidentification...

$EmptySlotsList

This notice was generated by \\server\path\to\ReportEmptySlots.ps1

"@

send-mailmessage -from $sender `
            -to $recipients `
            -subject "Empty Slots detected in $LibraryName" `
            -body "$body" `
            -priority High `
            -smtpServer $SMTPserver

}
